
development:
  adapter: mysql2
  database: twitta
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: twitta_test
  username: root
  password:
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: twitta
  username: root
  password:
  pool: 5
  timeout: 5000
